name: Retrieve Weather Data

on:
  schedule:
    - cron: '0 10 * * *'  # Run daily at 10 AM UTC
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print test message
      run: echo "The workflow has run successfully!"
