name: Fetch Weather Data

on:
  schedule:
    - cron: '0 10 * * *'  # Running the file daily at 10am
  workflow_dispatch:  # Enabling the manual triggering/running of the action

jobs:
  fetch_weather:
    runs-on: ubuntu-latest  # Stating I want the Ubuntu Virtual Machine to be used for the action.

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3  # Cloning the repository

    - name: Run weather.sh script
      run: |
        
        ./weather.sh         # Run the script

    - name: Commit and push weather data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add weather_data.json  # Add the weather data file (ensure the script generates this file)
        git commit -m "Update weather data"
        git push
