name: Fetch Weather Data

on:
  schedule:
    - cron: '0 10 * * *'  # Run daily at 10 AM UTC
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  fetch_weather:
    runs-on: ubuntu-latest  # Specify Ubuntu virtual machine for the action

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3  # This clones your repository

    - name: Print test message
      run: echo "The workflow has run successfully!"
