name: Fetch Weather Data

on:
  schedule:
    - cron: '0 10 * * *'  # Running the file daily at 10am
  workflow_dispatch:  # Enabling the manual triggering/running of the action

jobs:
  fetch_weather:
    runs-on: ubuntu-latest  # Use Ubuntu VM for the action

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: List files in the directory (Debugging)
      run: |
        ls -al  # List files to ensure `weather.sh` is present

    - name: Check if wget is installed (Debugging)
      run: |
        wget --version  # Ensure wget is installed in the runner

    - name: Ensure the script is executable
      run: |
        chmod +x weather.sh  # Make sure weather.sh is executable

    - name: Run weather.sh script
      run: |
        ./weather.sh  # Run the weather script

    - name: Check git status (Debugging)
      run: |
        git status  # Check if there are any changes after the script runs

    - name: List files after script runs
      run: |
        ls -al  # List files to see if the .json file was created

    - name: Commit and push weather data
      run: |
        git config --global user.name "Barry Egan"
        git config --global user.email "g00425649@atu.ie"
        git add *.json  # Add any .json files created by the script
        git commit -m "Updated weather data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
