name: Fetch Weather Data

on:
  schedule:
    - cron: '0 10 * * *'  # Indicating to run the file daily at 10am
  workflow_dispatch:  # Configuring the workflow to allow manual triggering

jobs:
  fetch_weather:
    runs-on: ubuntu-latest  # Specifying Ubuntu Virtual Machine

    permissions:
      contents: write  # To Allow pushes to the repository.

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3  # Cloning the repository

    - name: Print test message
      run: echo "The workflow has run successfully!"

    - name: Make weather.sh executable
      run: chmod +x .github/weather.sh

    - name: Run weather.sh script
      run: .github/weather.sh

    - name: Set up Git config
      run: |
          git config --global user.name "Barry Egan"
          git config --global user.email "g00425649@atu.ie"

    - name: Commit and push changes
      run: |
          git add .
          git commit -m "Update weather data"
          git push origin main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
